[package]
name = "sparkles"
description = "Capture execution flow of your Rust application with CPU cycle precision!"
version = "0.0.1"
edition = "2021"
license= "MIT"
repository = "https://github.com/skibon02/sparkles"

[dependencies]
bincode = "1.3.3"
log = { version = "0.4.21", default-features = false }
ringbuf = "0.4.1"
serde = { version = "1.0.203", features = ["derive"] }

[dev-dependencies]
simple_logger = "5.0.0"
tracing = "0.1.40"
puffin_http = "0.16.0"
puffin = { version = "0.19.0", features = ["packing"] }
tracing-timing = "0.6.0"
sparkles-macro = {path = "../sparkles-macro"}
